version: '3.8'

services:
    app:
        build: '.'
        networks:
            - local
        ports:
            - 8000:8000
        volumes:
            - ./app:/usr/src/app
            - ./todos.db:/usr/src/todos.db
    auth:
        build: '.'
        networks:
            - local
        ports:
            - 9000:9000
        entrypoint: uvicorn app.auth:app --host=0.0.0.0 --reload --port 9000
        volumes:
            - ./app:/usr/src/app
            - ./todos.db:/usr/src/todos.db
    db:
        image: postgres
        networks:
            - local
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: example

networks:
  local:
    name: local
